### ISSUE TITLE
Provide z7 archive or WSA installer

### ISSUE THREAD

**Issue by woodie** [vassilvk/slacker#14]
People buillding Docker microsoft/nanoserver images would appreciate a WSA download of the DevKit installer (MSI and EXE are not supported on Nano Server).

https://blogs.technet.microsoft.com/nanoserver/2015/11/18/installing-windows-server-apps-on-nano-server/

See also: https://sourceforge.net/p/p7zip/discussion/383043/thread/87a7a773/

**Comment by vassilvk** [comment]
@woodie - Ruby DevKit is distributed by the good folk behind the RubyInstaller project - I don't plan on distributing it separately from them.

I can suggest the following:

Since Ruby DevKit is distributed a self-extracting executable which simply dumps the DevKit in a folder, you can re-package it as a z7 archive.

Then in your Dockerfile you can RUN [these steps](https://github.com/vassilvk/slacker/wiki/Installing-Windows-Ruby-DevKit) but skip step one and replace step two with a call to z7 to extract the DevKit archive.

**Comment by vassilvk** [comment]
@woodie - to take your `nanoserver-ruby` image as an example, [at this point here](https://github.com/woodie/nanoserver-ruby/blob/master/Dockerfile#L17), instead of downloading the self-extracting executable of DevKit, you can ADD the DevKit z7 archive you've prepackaged and included with your repository.

**Comment by woodie** [comment]
Working with 7-Zip on Docker nanoserver images was a dead end, but there is progress.

As [described here](https://github.com/docker-library/ruby/issues/130), I got everything working on nanoserver by doing a multi-stage build (passing through a windowscoreserver).

Please take a look at my [nanoserver-ruby Dockerfile](https://github.com/woodie/nanoserver-ruby/blob/master/Dockerfile), and let my know if you think I'm doing something wrong by setting the path manually, and then calling dk.rb. There should only be one version of ruby in each container.

We should review [a linux-based ruby Dockerfile](https://github.com/docker-library/ruby/blob/b12b0fd99eed0dc416f3f85d4643be69c44e4fa7/2.1/alpine/Dockerfile
), and see what they are doing with all the environment variable setup.

**Comment by vassilvk** [comment]
It looks good - the multi-stage build trick is pretty cool.

I see no issues with hard-coding the path in config.yml -- you are in full control of the file system so there should be no conflicts or misconfiguration.

The linux-based image includes Bundler. Did you plan on including that with your image?

**Comment by woodie** [comment]
My goal is to have linux and nano base images appear identical from the standpoint of ruby, so I plan to enforce all the same versions of supporting tools (rake, gem, bundler) within reason. At the same time, I want to embrace the goals of DevKit to avoid stumbling across issues that DevKit has already resolved.

**Comment by vassilvk** [comment]
In this case I'd `gem install` Bundler and set up all the BUNDLE_* environment vars as per the official Ruby Docker image.

**Comment by vassilvk** [comment]
@woodie - I am closing this issue as there is no actionable item for the Slacker codebase.
